name: vimflowy
on:   [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-node@master
      with:
        node-version: '22'
      env:
        RUNNER_TEMP: "/tmp/"

    - run: npm install --legacy-peer-deps

    - run: npm run build
    - run: npm run verify
